on: push
name: 🚀 Deploy website via SFTP

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Upload via SFTP
      
      - name: 📂 Sync files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./
          remote_path: httpdocs/
          delete_remote_files: false
          port: 22
          local_path: './*'
          remote_path: './httpdocs/'
          sftp_only: true
